import React, { useState, useEffect } from 'react';
import { api } from '../../lib/api.js';
import { formatINR, formatDate, formatDateTime } from '../../lib/utils.js';
import { Download, FileSpreadsheet, CheckCircle2, Calendar } from 'lucide-react';

export const AdminReportsPage: React.FC = () => {
  const [report, setReport] = useState<any>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    api
      .get<any>('/admin/reports')
      .then(setReport)
      .catch(() => {})
      .finally(() => setIsLoading(false));
  }, []);

  const handleExportCSV = () => {
    if (!report?.transactions) return;

    let csv = 'Transaction ID,Type,Account,Amount,Reference Type,Description,Date\n';
    report.transactions.forEach((t: any) => {
      csv += `"${t.id}",` +
        `"${t.entryType}",` +
        `"${t.account}",` +
        `"${t.amount}",` +
        `"${t.referenceType}",` +
        `"${t.description.replace(/"/g, '""')}",` +
        `"${new Date(t.recordedAt).toISOString()}"\n`;
    });

    const blob = new Blob([csv], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Financial_Report_${new Date().toISOString().split('T')[0]}.csv`;
    a.click();
    window.URL.revokeObjectURL(url);
  };

  if (isLoading) {
    return (
      <div className="py-20 text-center space-y-3">
        <div className="w-8 h-8 border-4 border-brand-coral border-t-transparent rounded-full animate-spin mx-auto"></div>
        <p className="text-xs text-slate-500">Compiling financial report...</p>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-serif font-bold text-slate-900">Financial Reports & Statements</h1>
          <p className="text-xs text-slate-500">
            Certified double-entry ledger summaries, balance computations, and category breakdowns.
          </p>
        </div>

        <button
          onClick={handleExportCSV}
          className="py-2 px-3.5 bg-brand-navy hover:bg-brand-navyLight text-white text-xs font-bold rounded-xl transition flex items-center space-x-1.5 shadow-sm"
        >
          <Download className="w-3.5 h-3.5" />
          <span>Export Ledger as CSV</span>
        </button>
      </div>

      {/* Meta Box */}
      <div className="bg-white p-4 rounded-2xl border border-slate-200 text-xs flex flex-wrap items-center justify-between gap-3 text-slate-500">
        <div>
          <span className="font-semibold text-slate-700">Generated By:</span> {report?.generatedBy}
        </div>
        <div>
          <span className="font-semibold text-slate-700">Generation Timestamp:</span>{' '}
          {formatDateTime(report?.generatedAt)}
        </div>
        <div className="text-brand-green font-semibold flex items-center">
          <CheckCircle2 className="w-3.5 h-3.5 mr-1" /> Reconciled with Bank Statement
        </div>
      </div>

      {/* 5 Balance Statement Cards */}
      <div className="grid grid-cols-2 lg:grid-cols-5 gap-4">
        <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-sm space-y-1">
          <span className="text-[11px] font-semibold text-slate-400 uppercase">Opening Corpus</span>
          <div className="text-xl font-mono font-bold text-slate-800">
            {formatINR(report?.openingBalance || 0)}
          </div>
        </div>

        <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-sm space-y-1">
          <span className="text-[11px] font-semibold text-slate-400 uppercase">Total Verified Income</span>
          <div className="text-xl font-mono font-bold text-emerald-600">
            +{formatINR(report?.totalIncome || 0)}
          </div>
        </div>

        <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-sm space-y-1">
          <span className="text-[11px] font-semibold text-slate-400 uppercase">Approved Outflow</span>
          <div className="text-xl font-mono font-bold text-brand-coral">
            -{formatINR(report?.totalApprovedExpenses || 0)}
          </div>
        </div>

        <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-sm space-y-1">
          <span className="text-[11px] font-semibold text-slate-400 uppercase">Current Net Balance</span>
          <div className="text-xl font-mono font-bold text-brand-navy">
            {formatINR(report?.availableBalance || 0)}
          </div>
        </div>

        <div className="bg-white p-5 rounded-2xl border border-slate-200 shadow-sm space-y-1">
          <span className="text-[11px] font-semibold text-slate-400 uppercase">Closing Balance</span>
          <div className="text-xl font-mono font-bold text-brand-green">
            {formatINR(report?.closingBalance || 0)}
          </div>
        </div>
      </div>

      {/* Category Breakdown Table */}
      <div className="bg-white rounded-3xl border border-slate-200 shadow-sm p-6 space-y-4">
        <h3 className="text-base font-serif font-bold text-slate-900">Category-wise Expenditure Allocation</h3>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {(report?.expenseCategories || []).map((cat: any) => (
            <div key={cat.category} className="p-3 bg-slate-50 rounded-xl border border-slate-100 text-xs space-y-1">
              <div className="flex justify-between font-semibold text-slate-700">
                <span>{cat.categoryLabel}</span>
                <span className="text-brand-coral font-mono">{formatINR(cat.amount)}</span>
              </div>
              <div className="w-full bg-slate-200 rounded-full h-1.5 overflow-hidden">
                <div className="bg-brand-coral h-full rounded-full" style={{ width: `${cat.percentage}%` }}></div>
              </div>
              <div className="text-[10px] text-slate-400 text-right">{cat.percentage}% of total relief</div>
            </div>
          ))}
        </div>
      </div>

      {/* Recent Ledger Entries */}
      <div className="bg-white rounded-3xl border border-slate-200 shadow-sm overflow-hidden space-y-2 p-6">
        <h3 className="text-base font-serif font-bold text-slate-900 mb-2">Double-Entry Ledger Audit Trail</h3>
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead className="bg-slate-50 border-b border-slate-200 text-slate-500 uppercase tracking-wider font-semibold">
              <tr>
                <th className="py-2.5 px-3">Type</th>
                <th className="py-2.5 px-3">Description</th>
                <th className="py-2.5 px-3">Account</th>
                <th className="py-2.5 px-3">Amount</th>
                <th className="py-2.5 px-3 text-right">Recorded Date</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {(report?.transactions || []).map((t: any) => (
                <tr key={t.id} className="hover:bg-slate-50/70 transition">
                  <td className="py-2.5 px-3">
                    <span
                      className={`inline-block px-2 py-0.5 rounded font-mono text-[10px] font-bold ${
                        t.entryType === 'CREDIT' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'
                      }`}
                    >
                      {t.entryType}
                    </span>
                  </td>
                  <td className="py-2.5 px-3 font-medium text-slate-800">{t.description}</td>
                  <td className="py-2.5 px-3 text-slate-500 font-mono text-[11px]">{t.account}</td>
                  <td
                    className={`py-2.5 px-3 font-mono font-bold ${
                      t.entryType === 'CREDIT' ? 'text-green-700' : 'text-red-700'
                    }`}
                  >
                    {t.entryType === 'CREDIT' ? '+' : '-'}
                    {formatINR(t.amount)}
                  </td>
                  <td className="py-2.5 px-3 text-right text-slate-400">{formatDate(t.recordedAt)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
